management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  kafka:
    bootstrap-servers: localhost:9092
