input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if ![service_name] {
    mutate {
      add_field => { "service_name" => "unknown-service" }
    }
  }

  mutate {
    lowercase => [ "service_name" ]
    gsub => [ "service_name", "[^a-z0-9_-]", "-" ]
  }
}

output {
  elasticsearch {
    hosts => [ "http://elasticsearch:9200" ]
    index => "camp-%{service_name}-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
